general:
  output_dir: /content/drive/MyDrive/Colab Notebooks/SimCLR
  log_to_wandb: True
  checkpoint_freq: 10
data:
  dataset: dummy
  dataset_type: per_scan
  image_size: 224
  set_size: 3
  sample_width: 0.5
optim:
  lr: 0.07
  weight_decay: 1.0e-10
  workers: 8
  batch_size: 16
  epochs: 100
  device: cuda
model:
  type: simclr
  dedicated_deepset_mlp: False
  backbone:
    name: resnet50
